# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: run some exploration
      run: |
        set -x
        #sudo rm -rf /usr/local/go1* /usr/share/dotnet /usr/share/rust /usr/local/julia* /usr/lib/firefox
        #sudo apt-get purge llvm*
        #sudo apt-get autoremove
        sudo apt-get update
        sudo apt-get install libvirt-clients libvirt-daemon libvirt-daemon-system
        sudo service libvirtd start
        #find /usr -maxdepth 2 -mindepth 2 -type d | grep -v -E '^/(dev|proc|run|tmp|boot|root|sys)' | xargs -l du -sh 2>/dev/null | sort -h
        #df -h
        sudo virsh list
        sudo virsh list | grep foo
