# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: run some exploration
      run: |
        find / -maxdepth 2 -mindepth 2 | grep -v -E '^/(dev|proc|run|tmp|boot|root|sys)' | xargs -l du -sh 2>/dev/null | sort -h
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        set +e
        sudo apt-get update
        sudo apt install -y python3-apt python-apt libapt-pkg-dev build-essential python3-setuptools
        which python
        python -c "import apt"
    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: More info
      run: |
        set +e
        which python
        python -m pip install -U pip
        pip install -U setuptools wheel
        which pip
        pip install git+https://git.launchpad.net/ubuntu/+source/python-apt@applied/ubuntu/bionic-updates
        python -c "import apt"
        
