# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: run some exploration
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install apt-file
        sudo apt-file update
        apt-file search /usr/share/golang-1.12
        sudo apt-get purge aspnetcore-runtime-{2.1,2.2,3.0,3.1} aspcore-store-2.0.{0,3,5,6,7,8,9} aspnetcore-targeting-pack-3.{0,1} \
        dotnet-apphost-pack-3.{0,1} dotnet-dev-1.1.{11,13,14} dotnet-host dotnet-host-fxr-{1.1.9,1.1.10,1.1.11,1.1.12,1.1.13,2.0.7,2.0.9,2.1,2.2,3.0,3.1} \
        dotnet-runtime-{2.0.7,2.0.9,2.1,2.2,3.0}
        find /usr -maxdepth 2 -mindepth 2 | grep -v -E '^/(dev|proc|run|tmp|boot|root|sys)' | xargs -l du -sh 2>/dev/null | sort -h
        df -h
